### PR TITLE
Made Responsive

### PR DESCRIPTION
**Pull request by baibhav0305**
I have fixed the horizontal scrolling and also made it responsive.
Do consider my PR.

### CODE REVIEW

**Comment by baibhav0305** [comment]
@Nish251103 I have made it responsive entirely

**Comment by Nish251103** [comment]
Hello @baibhav0305  , There is a conflict with the style.css file due to recent file updates.
If you could please resolve it, I will merge it.
Thank You

**Comment by baibhav0305** [comment]
@Nish251103 the other guy has changed the code entirely and I don't think that is a wise decision

**Comment by Nish251103** [comment]
Okay no problem,
could you create a new branch??

**Comment by baibhav0305** [comment]
ok let me try

**Pull request merged**
