### PR TITLE
Fixed grids and horizontal scrolling format

### PR DESCRIPTION
**Pull request by varunsh17**
I have changed and added some new css and your grid system is a little bit weak so I fixed it ! . 
Just Do git checkout varunbranch and open with live server you can see the changes I have made and don't worry I have made another branch so your main code and branch won't be affected !

### CODE REVIEW

**Comment by varunsh17** [comment]
Reply ASAP @Nish251103

**Comment by Nish251103** [comment]
image

**Comment by varunsh17** [comment]
Yes buddy It is conflicting just accept the incoming changes after merging .

**Comment by Nish251103** [comment]
Thank you 😄

**Review by varunsh17 — COMMENTED** [review]
Can you see the changes I made ?

**Comment by Nish251103** [comment]
> Can you see the changes I made ?
yess

**Pull request merged**
